name: lychee

on:
  push:
  pull_request:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: lycheeverse/lychee-action@v1.0.8
      with:
        args: '--verbose --no-progress *.md'
